using System.Text;

namespace Nami.Interop;

/// <summary>
/// Emits a compile-time-typed C# projection of an IL2CPP game's metadata: one static class per
/// game type exposing <see cref="GameClass"/>-style handles (Nami.Tide resolves members by name
/// at runtime; the projection gives mods IDE discoverability and compile-time-checked names).
/// Each <see cref="GameClass"/> is materialized lazily on first use and cached per type —
/// resolution (and the underlying native member lookup) runs once, not per call.
/// The generated file is plain source — mods include it and reference Nami.Tide.
/// </summary>
public static class ProjectionWriter
{
    /// <summary>
    /// Generates the projection source for the given image's public top-level types.
    /// </summary>
    /// <param name="metadata">The parsed metadata.</param>
    /// <param name="imageName">Image (assembly) name, e.g. "Assembly-CSharp.dll".</param>
    /// <param name="rootNamespace">Root C# namespace of the generated file.</param>
    public static string Generate(Il2CppMetadata metadata, string imageName, string rootNamespace = "GameInterop")
    {
        var types = metadata.TypesInImage(imageName)
            .Where(t => t.IsPublic && !string.IsNullOrEmpty(t.Name))
            .OrderBy(t => t.FullName, StringComparer.OrdinalIgnoreCase)
            .ToList();

        rootNamespace = SanitizeNamespace(rootNamespace);
        var typesClass = Unique($"{CSharpSafe(StripDll(imageName))}Types", new HashSet<string>(StringComparer.Ordinal));
        var methodsClass = Unique($"{CSharpSafe(StripDll(imageName))}Methods", new HashSet<string>(StringComparer.Ordinal) { typesClass });

        var typeSafeNames = new HashSet<string>(StringComparer.Ordinal);
        var typeLines = new List<string>(types.Count * 6);
        foreach (var type in types)
        {
            // ponytail: collisions (A.B vs A_B) get a numeric suffix so output always compiles.
            var safe = Unique(CSharpSafe(type.FullName), typeSafeNames);
            typeLines.Add($"    private static GameClass _{safe};");
            typeLines.Add(string.Empty);
            typeLines.Add("    /// <summary>");
            typeLines.Add($"    /// {Escape(type.FullName)} ({CountSummary(type)}).");
            typeLines.Add("    /// </summary>");
            typeLines.Add($"    public static GameClass {safe} => _{safe} ??= GameClass.Resolve(");
            typeLines.Add($"        \"{Escape(StripDll(imageName))}\", \"{Escape(type.Namespace)}\", \"{Escape(type.Name)}\");");
            typeLines.Add(string.Empty);
        }

        var sb = new StringBuilder(64 * 1024);
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine($"//     nami interop projection of {imageName}");
        sb.AppendLine($"//     metadata version {metadata.MetadataVersion}; {types.Count} public top-level types");
        sb.AppendLine("//     Generated by Nami — do not edit by hand; regenerate after game updates.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine();
        sb.AppendLine($"namespace {rootNamespace};");
        sb.AppendLine();
        sb.AppendLine("using Nami;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>Static accessors for the game's public types. Each GameClass is resolved through Nami.Tide on first use and cached for the process lifetime.</summary>");
        sb.AppendLine($"public static partial class {typesClass}");
        sb.AppendLine("{");
        foreach (var line in typeLines)
        {
            sb.AppendLine(line);
        }

        sb.AppendLine("}");

        // Method-name constants per type. Overloads share one const (the value is the
        // runtime name); the comment records each overload's shape. Runtime calls stay
        // name-based, so collapsing overloads keeps call sites checked without duplicates.
        var emittedMethodClasses = false;
        var usedNested = new HashSet<string>(StringComparer.Ordinal);
        foreach (var type in types)
        {
            var methods = metadata.MethodsOf(type)
                .GroupBy(m => m.Name, StringComparer.Ordinal)
                .OrderBy(g => g.Key, StringComparer.Ordinal)
                .ToList();
            if (methods.Count == 0)
            {
                continue;
            }

            if (!emittedMethodClasses)
            {
                sb.AppendLine();
                sb.AppendLine($"/// <summary>Method names per type (signatures noted; call via GameClass/GameObject).</summary>");
                sb.AppendLine($"public static partial class {methodsClass}");
                sb.AppendLine("{");
                emittedMethodClasses = true;
            }

            sb.AppendLine($"    /// <summary>Method names of {Escape(type.FullName)}.</summary>");
            sb.AppendLine($"    public static partial class {Unique(CSharpSafe(type.FullName), usedNested)}");
            sb.AppendLine("    {");

            var used = new HashSet<string>(StringComparer.Ordinal);
            foreach (var group in methods)
            {
                var safe = Unique(CSharpSafe(group.Key), used);
                var shapes = string.Join(", ", group.Select(m => $"{(m.IsStatic ? "static" : "instance")}({m.ParameterCount})"));
                sb.AppendLine($"        /// <summary>{Escape(group.Key)}: {shapes}.</summary>");
                // A game method named like an object member (ToString/Equals/…) would raise
                // CS0108 without `new`; every other name emits a plain const (no CS0109).
                var hide = HidesObjectMember(safe) ? "new " : string.Empty;
                sb.AppendLine($"        public {hide}const string {safe} = \"{Escape(group.Key)}\";");
            }

            sb.AppendLine("    }");
        }

        if (emittedMethodClasses)
        {
            sb.AppendLine("}");
        }

        return sb.ToString();
    }

    private static string CountSummary(Il2CppTypeInfo t) =>
        $"{t.MethodCount} method(s), {t.FieldCount} field(s), {t.PropertyCount} propert{(t.PropertyCount == 1 ? "y" : "ies")}";

    private static string StripDll(string name) =>
        name.EndsWith(".dll", StringComparison.OrdinalIgnoreCase) ? name[..^4] : name;

    /// <summary>Makes an identifier C#-safe (namespaces/generics/escapes collapse to underscores).</summary>
    private static string CSharpSafe(string name)
    {
        if (string.IsNullOrEmpty(name))
        {
            return "_";
        }

        var chars = name.Select(c => char.IsLetterOrDigit(c) || c == '_' ? c : '_').ToArray();
        var safe = new string(chars);
        if (safe.Length == 0)
        {
            return "_";
        }

        if (char.IsDigit(safe[0]))
        {
            safe = "_" + safe;
        }

        return IsKeyword(safe) ? "@" + safe : safe;
    }

    private static string Unique(string candidate, HashSet<string> used)
    {
        if (used.Add(candidate))
        {
            return candidate;
        }

        for (var i = 2; ; i++)
        {
            var suffixed = $"{candidate}_{i}";
            if (used.Add(suffixed))
            {
                return suffixed;
            }
        }
    }

    private static string SanitizeNamespace(string rootNamespace)
    {
        if (string.IsNullOrWhiteSpace(rootNamespace))
        {
            return "GameInterop";
        }

        return string.Join(".", rootNamespace.Split('.').Select(p => CSharpSafe(p.Trim())));
    }

    /// <summary>Names that would hide an inherited object member as a const (CS0108).</summary>
    private static bool HidesObjectMember(string safe) => safe is
        "ToString" or "GetHashCode" or "Equals" or "GetType";

    private static bool IsKeyword(string s) => s switch
    {
        "abstract" or "as" or "base" or "bool" or "break" or "byte" or "case" or "catch"
            or "char" or "checked" or "class" or "const" or "continue" or "decimal" or "default"
            or "delegate" or "do" or "double" or "else" or "enum" or "event" or "explicit"
            or "extern" or "false" or "finally" or "fixed" or "float" or "for" or "foreach"
            or "goto" or "if" or "implicit" or "in" or "int" or "interface" or "internal"
            or "is" or "lock" or "long" or "namespace" or "new" or "null" or "object"
            or "operator" or "out" or "override" or "params" or "private" or "protected"
            or "public" or "readonly" or "ref" or "return" or "sbyte" or "sealed" or "short"
            or "sizeof" or "stackalloc" or "static" or "string" or "struct" or "switch"
            or "this" or "throw" or "true" or "try" or "typeof" or "uint" or "ulong"
            or "unchecked" or "unsafe" or "ushort" or "using" or "virtual" or "void"
            or "volatile" or "while" => true,
        _ => false,
    };

    private static string Escape(string s) => s
        .Replace("\\", "\\\\")
        .Replace("\"", "\\\"")
        .Replace("\r", "\\r")
        .Replace("\n", "\\n");
}
